// Generated by CoffeeScript 1.6.3
(function() {
  var bufferParser, debug, exports;

  debug = require('debug')('connect-tcp:middleware:bufferParser');

  bufferParser = exports = module.exports = function() {
    var middleware;
    middleware = function(req, res, next) {
      req.data = req.buffer.toString();
      req.data = req.data.replace(/^\s+|\s+$/g, "");
      return next();
    };
    return middleware;
  };

}).call(this);
