// Generated by CoffeeScript 1.6.3
(function() {
  var debug, echo, exports;

  debug = require('debug')('connect-tcp:middleware:echo');

  echo = exports = module.exports = function() {
    var middleware;
    middleware = function(req, res, next) {
      debug("write " + req.buffer.length + " bytes");
      res.write(req.buffer);
      return next();
    };
    return middleware;
  };

}).call(this);
