// Generated by CoffeeScript 1.6.3
(function() {
  var debug, exports, logger;

  debug = require('debug')('connect-tcp:middleware:logger');

  logger = exports = module.exports = function(options) {
    if ('object' === typeof options) {
      if (options == null) {
        options = {};
      }
    } else if (options) {
      options = {
        format: options
      };
    } else {
      options = {};
    }
    logger = function(connection, next) {
      debug("Message from logger");
      return next();
    };
    return logger;
  };

}).call(this);
