// Generated by CoffeeScript 1.6.3
(function() {
  var debug, exports, logger;

  debug = require('debug')('connect-tcp:middleware:logger');

  logger = exports = module.exports = function(options) {
    if ('object' === typeof options) {
      if (options == null) {
        options = {};
      }
    } else if (options) {
      options = {
        format: options
      };
    } else {
      options = {};
    }
    logger = function(req, res, next) {
      debug("Message from logger");
      return next();
    };
    return logger;
  };

  module.exports.sock_logger = function(options) {
    var sock_logger;
    sock_logger = function(connection, next) {
      debug("Message from sock_logger");
      connection.on('end', function() {
        return debug('message from sock_logger on end');
      });
      connection.on('data', function() {
        return debug('message from sock_logger on data');
      });
      connection.on('error', function() {
        return debug('message from sock_logger on error');
      });
      return next();
    };
    return sock_logger;
  };

}).call(this);
