// Generated by CoffeeScript 1.6.3
(function() {
  var app, debug, exports, net, utils;

  utils = require('./utils');

  debug = require('debug')('connect-tcp:dispatcher');

  net = require('net');

  exports = module.exports = app = {};

  app.use = function(fn) {
    debug("use %s", fn.name || 'anonymous');
    this.stack.push({
      handle: fn
    });
    return this;
  };

  app.handle = function(connection, out) {
    var index, next, stack;
    stack = this.stack;
    index = 0;
    next = function(err) {
      var arity, e, layer;
      layer = stack[index++];
      if (!layer) {
        if (out) {
          return out(err);
        }
        connection.end();
        return;
      }
      try {
        arity = layer.handle.length;
        if (err) {
          if (arity === 3) {
            return layer.handle(err, connection, next);
          } else {
            return next(err);
          }
        } else if (arity < 3) {
          return layer.handle(connection, next);
        } else {
          return next();
        }
      } catch (_error) {
        e = _error;
        return next(e);
      }
    };
    return next();
  };

  app.listen = function() {
    var server;
    server = net.createServer(this);
    return server.listen.apply(server, arguments);
  };

}).call(this);
