// Generated by CoffeeScript 1.6.3
(function() {
  exports.merge = function(a, b) {
    var key;
    if (a && b) {
      for (key in b) {
        a[key] = b[key];
      }
    }
    return a;
  };

}).call(this);
