// Generated by CoffeeScript 1.6.3
(function() {
  var connect_tcp, server;

  connect_tcp = require('..');

  server = connect_tcp.createServer();

  server.use(connect_tcp.echo());

  server.listen(3045, function() {
    return console.log("listening on port 3045");
  });

}).call(this);
