// Generated by CoffeeScript 1.6.3
(function() {
  var connect_tcp, debug, server;

  debug = require('debug')('connect-tcp:examples:echo');

  connect_tcp = require('..');

  server = connect_tcp.createServer();

  server.use(connect_tcp.logger());

  server.sock_use(connect_tcp.logger.sock_logger());

  server.use(function(req, res, next) {
    debug('converting buffer');
    req.data = req.buffer.toString();
    req.data = req.data.replace(/^\s+|\s+$/g, "");
    return next();
  });

  server.use(function(req, res, next) {
    debug('uppercasing data');
    req.data = req.data.toUpperCase();
    return next();
  });

  server.use(function(req, res, next) {
    var correspondances, exp, translation;
    debug('1337ing data');
    correspondances = {
      0: /[oO]/,
      1: /[lL]/,
      2: /[zZ]/,
      3: /[eE]/,
      4: /[aA]/,
      5: /[sS]/,
      6: /[gG]/,
      7: /[tT]/,
      8: /[bB]/
    };
    for (translation in correspondances) {
      exp = correspondances[translation];
      req.data = req.data.replace(exp, translation.toString());
    }
    return next();
  });

  server.use(function(req, res, next) {
    debug('reversing letters');
    req.data = req.data.split('').reverse().join('');
    return next();
  });

  server.use(function(req, res, next) {
    debug('sending back data', req.data);
    res.send(req.data);
    return next();
  });

  server.listen(3044, function() {
    return debug("listening on port 3044");
  });

}).call(this);
