// Generated by CoffeeScript 1.6.3
(function() {
  var connect_tcp, server;

  connect_tcp = require('..');

  server = connect_tcp.createServer();

  server.use(connect_tcp.bufferParser());

  server.use(function(req, res, next) {
    res.send(req.data);
    return next();
  });

  server.listen(3045, function() {
    return console.log("listening on port 3045");
  });

}).call(this);
