// Generated by CoffeeScript 1.6.3
(function() {
  var connect_tcp, debug, server;

  debug = require('debug')('connect-tcp:examples:logger');

  connect_tcp = require('..');

  connect_tcp.createServer(connect_tcp.logger()).listen(3042, function() {
    return debug("listening on port 3042");
  });

  server = connect_tcp.createServer();

  server.use(connect_tcp.logger());

  server.listen(3043, function() {
    return debug("listening on port 3043");
  });

}).call(this);
