// Generated by CoffeeScript 1.6.3
(function() {
  var connect_tcp, server;

  connect_tcp = require('..');

  server = connect_tcp.createServer();

  server.use(function(req, res) {
    var _base;
    if ((_base = req.session).line == null) {
      _base.line = 0;
    }
    req.session.line++;
    return res.send("line = " + req.session.line);
  });

  server.listen(3046, function() {
    return console.log("listening on port 3046");
  });

}).call(this);
